# Bun configuration file
# https://bun.sh/docs/runtime/bunfig

[install]
# Install configuration
optional = true
dev = true
peer = true

[run]
# Run configuration
shell = "system"

[test]
# Test configuration
